const LANGUAGES = [
  { id: 'sq', label: 'Shqip' },
  { id: 'en', label: 'English' },
  { id: 'it', label: 'Italiano' },
  { id: 'de', label: 'Deutsch' },
  { id: 'fr', label: 'Français' },
  { id: 'es', label: 'Español' },
  { id: 'tr', label: 'Türkçe' },
  { id: 'el', label: 'Ελληνικά' }
];

const CATEGORIES = [
  'Të gjitha',
  'Biologjia dhe sjellja e bletës',
  'Koshere dhe pajisje',
  'Menaxhimi i kolonisë',
  'Mbarështimi i mbretëreshës',
  'Shëndeti dhe bio-siguria',
  'Produkte dhe përpunim',
  'Ushqimi dhe fenologjia',
  'Bimët, pllenimi dhe mjedisi'
];

const term = (id, c, d, sq, en, it, de, fr, es, tr, el, a = {}) => ({
  id, c, d, t: { sq, en, it, de, fr, es, tr, el }, a
});

const GLOSSARY = [
  // Biologjia dhe sjellja e bletës
  term('worker-bee', 'Biologjia dhe sjellja e bletës', 'Femër sterile që kryen punët kryesore të kolonisë.', 'bletë punëtore', 'worker bee', 'ape operaia', 'Arbeiterbiene', 'abeille ouvrière', 'abeja obrera', 'işçi arı', 'εργάτρια μέλισσα', { en:['worker'], tr:['işçi'], el:['εργάτρια'] }),
  term('queen-bee', 'Biologjia dhe sjellja e bletës', 'Femra kryesore riprodhuese e kolonisë.', 'bletë mbretëreshë', 'queen bee', 'ape regina', 'Bienenkönigin', 'reine des abeilles', 'abeja reina', 'ana arı', 'βασίλισσα μέλισσα', { en:['queen'], tr:['kraliçe arı'], el:['βασίλισσα'] }),
  term('drone', 'Biologjia dhe sjellja e bletës', 'Bleta mashkullore, e zhvilluar nga vezë e pafekonduar.', 'bletë mashkullore', 'drone', 'fuco', 'Drohne', 'faux-bourdon', 'zángano', 'erkek arı', 'κηφήνας'),
  term('egg', 'Biologjia dhe sjellja e bletës', 'Faza e parë e zhvillimit të bletës.', 'vezë', 'egg', 'uovo', 'Ei', 'œuf', 'huevo', 'yumurta', 'αυγό'),
  term('larva', 'Biologjia dhe sjellja e bletës', 'Faza e zhvillimit ndërmjet vezës dhe pupës.', 'larvë', 'larva', 'larva', 'Larve', 'larve', 'larva', 'larva', 'προνύμφη'),
  term('pupa', 'Biologjia dhe sjellja e bletës', 'Faza e zhvillimit para daljes së bletës së rritur.', 'pupë', 'pupa', 'pupa', 'Puppe', 'nymphe', 'pupa', 'pupa', 'νύμφη'),
  term('brood', 'Biologjia dhe sjellja e bletës', 'Tërësia e vezëve, larvave dhe pupave në hoje.', 'pjellë', 'brood', 'covata', 'Brut', 'couvain', 'cría', 'yavru', 'γόνος'),
  term('open-brood', 'Biologjia dhe sjellja e bletës', 'Vezë dhe larva në qeliza të pambyllura.', 'pjellë e hapur', 'open brood', 'covata aperta', 'offene Brut', 'couvain ouvert', 'cría abierta', 'açık yavru', 'ανοιχτός γόνος'),
  term('sealed-brood', 'Biologjia dhe sjellja e bletës', 'Pjellë në qeliza të mbyllura me kapak dylli.', 'pjellë e mbyllur', 'capped brood', 'covata opercolata', 'verdeckelte Brut', 'couvain operculé', 'cría operculada', 'kapalı yavru', 'σφραγισμένος γόνος'),
  term('brood-pattern', 'Biologjia dhe sjellja e bletës', 'Shpërndarja e pjellës në kornizë, tregues i gjendjes së kolonisë.', 'model i pjellës', 'brood pattern', 'schema di covata', 'Brutbild', 'motif de couvain', 'patrón de cría', 'yavru düzeni', 'διάταξη γόνου'),
  term('queen-cell', 'Biologjia dhe sjellja e bletës', 'Qelizë e zgjatur ku zhvillohet mbretëresha e re.', 'qelizë mbretërore', 'queen cell', 'cella reale', 'Weiselzelle', 'cellule royale', 'celda real', 'ana arı memesi', 'βασιλικό κελί'),
  term('queen-cup', 'Biologjia dhe sjellja e bletës', 'Bazë e vogël qelizore për rritjen e një mbretëreshe.', 'kupë mbretërore', 'queen cup', 'coppa reale', 'Weiselnäpfchen', 'cupule royale', 'cúpula real', 'ana arı yüksüğü', 'βασιλικό κύπελλο'),
  term('virgin-queen', 'Biologjia dhe sjellja e bletës', 'Mbretëreshë e re që ende nuk është çiftëzuar.', 'mbretëreshë e virgjër', 'virgin queen', 'regina vergine', 'unbegattete Königin', 'reine vierge', 'reina virgen', 'çiftleşmemiş ana arı', 'παρθένα βασίλισσα'),
  term('mated-queen', 'Biologjia dhe sjellja e bletës', 'Mbretëreshë që është çiftëzuar dhe mund të vendosë vezë të fekonduara.', 'mbretëreshë e çiftëzuar', 'mated queen', 'regina fecondata', 'begattete Königin', 'reine fécondée', 'reina fecundada', 'çiftleşmiş ana arı', 'γονιμοποιημένη βασίλισσα'),
  term('nurse-bee', 'Biologjia dhe sjellja e bletës', 'Punëtore e re që ushqen dhe kujdeset për pjellën.', 'bletë kujdestare', 'nurse bee', 'ape nutrice', 'Ammenbiene', 'abeille nourrice', 'abeja nodriza', 'bakıcı arı', 'παραμάνα μέλισσα'),
  term('forager', 'Biologjia dhe sjellja e bletës', 'Punëtore që mbledh nektar, polen, ujë ose propolis.', 'bletë mbledhëse', 'forager', 'ape bottinatrice', 'Sammelbiene', 'abeille butineuse', 'abeja pecoreadora', 'tarlacı arı', 'συλλέκτρια μέλισσα'),
  term('guard-bee', 'Biologjia dhe sjellja e bletës', 'Punëtore që ruan hyrjen e kosheres.', 'bletë roje', 'guard bee', 'ape guardiana', 'Wächterbiene', 'abeille gardienne', 'abeja guardiana', 'bekçi arı', 'φρουρός μέλισσα'),
  term('scout-bee', 'Biologjia dhe sjellja e bletës', 'Punëtore që kërkon burime ushqimore ose vende folezimi.', 'bletë zbulues', 'scout bee', 'ape esploratrice', 'Spurbiene', 'abeille éclaireuse', 'abeja exploradora', 'keşifçi arı', 'ανιχνεύτρια μέλισσα'),
  term('pollen-basket', 'Biologjia dhe sjellja e bletës', 'Strukturë në këmbën e pasme për bartjen e polenit.', 'kosh poleni', 'pollen basket', 'cestello del polline', 'Pollenkörbchen', 'corbeille à pollen', 'cesta de polen', 'polen sepeti', 'καλαθάκι γύρης'),
  term('proboscis', 'Biologjia dhe sjellja e bletës', 'Pjesa gojore me të cilën bleta thith nektarin.', 'proboscis', 'proboscis', 'spiritromba', 'Rüssel', 'trompe', 'probóscide', 'hortum', 'προβοσκίδα'),
  term('abdomen', 'Biologjia dhe sjellja e bletës', 'Pjesa e pasme e trupit të bletës.', 'abdomen', 'abdomen', 'addome', 'Hinterleib', 'abdomen', 'abdomen', 'karın', 'κοιλιά'),
  term('thorax', 'Biologjia dhe sjellja e bletës', 'Pjesa e mesme e trupit ku lidhen këmbët dhe krahët.', 'toraks', 'thorax', 'torace', 'Thorax', 'thorax', 'tórax', 'göğüs', 'θώρακας'),
  term('antenna', 'Biologjia dhe sjellja e bletës', 'Organ shqisor i çiftëzuar në kokën e bletës.', 'antenë', 'antenna', 'antenna', 'Fühler', 'antenne', 'antena', 'anten', 'κεραία'),
  term('wax-gland', 'Biologjia dhe sjellja e bletës', 'Gjendër e punëtores që prodhon dyllin.', 'gjendër dylli', 'wax gland', 'ghiandola ceripara', 'Wachsdrüse', 'glande cirière', 'glándula cerera', 'mum bezi', 'κερογόνος αδένας'),
  term('queen-pheromone', 'Biologjia dhe sjellja e bletës', 'Sinjal kimik i prodhuar nga mbretëresha.', 'feromon i mbretëreshës', 'queen pheromone', 'feromone della regina', 'Königinnenpheromon', 'phéromone royale', 'feromona de la reina', 'ana arı feromonu', 'φερομόνη βασίλισσας'),
  term('waggle-dance', 'Biologjia dhe sjellja e bletës', 'Lëvizje komunikuese që tregon drejtimin dhe largësinë e burimit ushqimor.', 'vallëzim tundës', 'waggle dance', 'danza dell’addome', 'Schwänzeltanz', 'danse frétillante', 'danza del meneo', 'sallanma dansı', 'χορός της κοιλιάς'),
  term('trophallaxis', 'Biologjia dhe sjellja e bletës', 'Shkëmbimi i ushqimit dhe sinjaleve nga goja në gojë.', 'trofalaksi', 'trophallaxis', 'trofallassi', 'Trophallaxis', 'trophallaxie', 'trofalaxia', 'trofallaksi', 'τροφαλλάξια'),
  term('bee-space', 'Biologjia dhe sjellja e bletës', 'Hapësira funksionale që bletët e lënë të lirë për lëvizje.', 'hapësirë blete', 'bee space', 'spazio d’ape', 'Bienenabstand', 'espace abeille', 'espacio de abeja', 'arı boşluğu', 'διάκενο μέλισσας'),

  // Koshere dhe pajisje
  term('hive', 'Koshere dhe pajisje', 'Strehë artificiale për një koloni bletësh.', 'koshere', 'beehive', 'arnia', 'Bienenstock', 'ruche', 'colmena', 'kovan', 'κυψέλη', { en:['hive'], tr:['arı kovanı'], el:['μελισσοκυψέλη'] }),
  term('langstroth-hive', 'Koshere dhe pajisje', 'Tip koshereje me korniza të lëvizshme.', 'koshere Langstroth', 'Langstroth hive', 'arnia Langstroth', 'Langstroth-Beute', 'ruche Langstroth', 'colmena Langstroth', 'Langstroth kovanı', 'κυψέλη Langstroth'),
  term('nucleus-hive', 'Koshere dhe pajisje', 'Koshere e vogël për një koloni të vogël ose mbretëresha.', 'koshere bërthamë', 'nucleus hive', 'arnia nucleo', 'Begattungskasten', 'ruchette', 'colmena núcleo', 'ruşet kovan', 'κυψέλη παραφυάδας', { en:['nuc'], it:['nucleo'], tr:['nük kovan'] }),
  term('frame', 'Koshere dhe pajisje', 'Element që mban hojen në koshere.', 'kornizë', 'frame', 'telaino', 'Rähmchen', 'cadre', 'cuadro', 'çerçeve', 'πλαίσιο'),
  term('top-bar', 'Koshere dhe pajisje', 'Pjesa e sipërme horizontale e kornizës.', 'shirit i sipërm', 'top bar', 'listello superiore', 'Oberträger', 'tête de cadre', 'listón superior', 'üst çıta', 'επάνω πήχης'),
  term('comb', 'Koshere dhe pajisje', 'Strukturë qelizore prej dylli për pjellë dhe rezerva ushqimi.', 'hoje', 'honeycomb', 'favo', 'Wabe', 'rayon', 'panal', 'petek', 'κηρήθρα'),
  term('foundation', 'Koshere dhe pajisje', 'Fletë me bazë qelizash që vendoset në kornizë.', 'fletë dylli', 'wax foundation', 'foglio cereo', 'Mittelwand', 'cire gaufrée', 'lámina de cera estampada', 'temel petek', 'φύλλο κηρήθρας'),
  term('drawn-comb', 'Koshere dhe pajisje', 'Hoje me qeliza të ndërtuara plotësisht nga bletët.', 'hoje e ndërtuar', 'drawn comb', 'favo costruito', 'ausgebaute Wabe', 'rayon bâti', 'panal estirado', 'kabartılmış petek', 'χτισμένη κηρήθρα'),
  term('brood-chamber', 'Koshere dhe pajisje', 'Pjesa e kosheres ku rritet pjella.', 'dhomë pjelle', 'brood chamber', 'nido', 'Brutraum', 'corps de ruche', 'cámara de cría', 'kuluçkalık', 'γονοφωλιά'),
  term('honey-super', 'Koshere dhe pajisje', 'Kuti mbi dhomën e pjellës për rezervat e mjaltit.', 'kati i mjaltit', 'honey super', 'melario', 'Honigraum', 'hausse', 'alza melaria', 'ballık', 'μελιτοθάλαμος'),
  term('queen-excluder', 'Koshere dhe pajisje', 'Rrjetë që lejon punëtoret, por kufizon mbretëreshën dhe meshkujt.', 'ndarës mbretëreshe', 'queen excluder', 'escludiregina', 'Absperrgitter', 'grille à reine', 'excluidor de reinas', 'ana arı ızgarası', 'βασιλικό διάφραγμα'),
  term('inner-cover', 'Koshere dhe pajisje', 'Kapak i brendshëm nën kapakun e jashtëm.', 'kapak i brendshëm', 'inner cover', 'coprifavo', 'Zwischendeckel', 'couvre-cadres', 'entretapa', 'iç kapak', 'εσωτερικό καπάκι'),
  term('bottom-board', 'Koshere dhe pajisje', 'Bazamenti ose dyshemeja e kosheres.', 'bazament koshereje', 'bottom board', 'fondo dell’arnia', 'Bodenbrett', 'plancher de ruche', 'fondo de colmena', 'kovan tabanı', 'πάτος κυψέλης'),
  term('screened-bottom-board', 'Koshere dhe pajisje', 'Bazament me rrjetë për ventilim dhe monitorim të rënies së marimangave.', 'bazament me rrjetë', 'screened bottom board', 'fondo antivarroa', 'Gitterboden', 'plancher grillagé', 'fondo sanitario', 'tel taban', 'διάτρητος πάτος'),
  term('entrance-reducer', 'Koshere dhe pajisje', 'Pjesë që ngushton hyrjen e kosheres.', 'ngushtues hyrjeje', 'entrance reducer', 'riduttore d’ingresso', 'Fluglochkeil', 'réducteur d’entrée', 'reductor de piquera', 'uçuş deliği daraltıcı', 'μειωτήρας εισόδου'),
  term('hive-stand', 'Koshere dhe pajisje', 'Mbështetëse që e ngre kosheres mbi tokë.', 'mbajtëse koshereje', 'hive stand', 'supporto per arnia', 'Beutenbock', 'support de ruche', 'soporte de colmena', 'kovan sehpası', 'βάση κυψέλης'),
  term('smoker', 'Koshere dhe pajisje', 'Pajisje që prodhon tym për qetësimin e bletëve.', 'tymosëse', 'bee smoker', 'affumicatore', 'Smoker', 'enfumoir', 'ahumador', 'körük', 'καπνιστήρι'),
  term('hive-tool', 'Koshere dhe pajisje', 'Mjet metalik për hapjen dhe lëvizjen e kornizave.', 'daltë bletari', 'hive tool', 'leva da apicoltore', 'Stockmeißel', 'lève-cadres', 'palanca apícola', 'kovan keski', 'ξέστρο μελισσοκομίας'),
  term('bee-brush', 'Koshere dhe pajisje', 'Furçë e butë për largimin e bletëve nga kornizat.', 'furçë bletësh', 'bee brush', 'spazzola per api', 'Bienenbürste', 'brosse à abeilles', 'cepillo para abejas', 'arı fırçası', 'βούρτσα μελισσών'),
  term('bee-escape', 'Koshere dhe pajisje', 'Pajisje njëdrejtimëshe për largimin e bletëve nga kati i mjaltit.', 'dalje njëdrejtimëshe për bletë', 'bee escape', 'apiscampo', 'Bienenflucht', 'chasse-abeilles', 'escape de abejas', 'arı kaçıran', 'διαφυγή μελισσών'),
  term('feeder', 'Koshere dhe pajisje', 'Pajisje për dhënien e ushqimit suplementar.', 'ushqyese', 'feeder', 'nutritore', 'Futtertrog', 'nourrisseur', 'alimentador', 'yemlik', 'τροφοδότης'),
  term('pollen-trap', 'Koshere dhe pajisje', 'Pajisje që mbledh një pjesë të polenit nga bletët hyrëse.', 'kurth poleni', 'pollen trap', 'trappola per polline', 'Pollenfalle', 'trappe à pollen', 'trampa de polen', 'polen tuzağı', 'γυρεοπαγίδα'),
  term('extractor', 'Koshere dhe pajisje', 'Makineri centrifugale për nxjerrjen e mjaltit nga hoje.', 'ekstraktor mjalti', 'honey extractor', 'smielatore', 'Honigschleuder', 'extracteur de miel', 'extractor de miel', 'bal süzme makinesi', 'μελιτοεξαγωγέας'),
  term('uncapping-knife', 'Koshere dhe pajisje', 'Thikë për heqjen e kapakëve të dyllit nga qelizat e mjaltit.', 'thikë çkapakuese', 'uncapping knife', 'coltello disopercolatore', 'Entdeckelungsmesser', 'couteau à désoperculer', 'cuchillo desoperculador', 'sır alma bıçağı', 'μαχαίρι απολεπισμού'),
  term('uncapping-fork', 'Koshere dhe pajisje', 'Pirun për çkapakimin e qelizave të mjaltit.', 'pirun çkapakues', 'uncapping fork', 'forchetta disopercolatrice', 'Entdeckelungsgabel', 'fourchette à désoperculer', 'tenedor desoperculador', 'sır alma çatalı', 'πιρούνι απολεπισμού'),
  term('refractometer', 'Koshere dhe pajisje', 'Instrument për matjen e lagështisë së mjaltit.', 'refraktometër', 'refractometer', 'rifrattometro', 'Refraktometer', 'réfractomètre', 'refractómetro', 'refraktometre', 'διαθλασίμετρο'),

  // Menaxhimi i kolonisë
  term('apiary', 'Menaxhimi i kolonisë', 'Vend ku mbahen një ose më shumë koshere.', 'bletore', 'apiary', 'apiario', 'Bienenstand', 'rucher', 'apiario', 'arı kovanlığı', 'μελισσοκομείο', { en:['bee yard'], tr:['arılık'] }),
  term('apiculture', 'Menaxhimi i kolonisë', 'Shkenca dhe praktika e rritjes së bletëve të mjaltit.', 'bletari', 'apiculture', 'apicoltura', 'Imkerei', 'apiculture', 'apicultura', 'arıcılık', 'μελισσοκομία', { sq:['bletaria'] }),
  term('hive-inspection', 'Menaxhimi i kolonisë', 'Kontroll i sistematik i gjendjes së kolonisë.', 'inspektim i kosheres', 'hive inspection', 'ispezione dell’arnia', 'Völkerdurchsicht', 'visite de ruche', 'inspección de la colmena', 'kovan kontrolü', 'επιθεώρηση κυψέλης'),
  term('colony-split', 'Menaxhimi i kolonisë', 'Ndarja e një kolonie në njësi të reja.', 'ndarje kolonie', 'colony split', 'divisione della colonia', 'Ablegerbildung', 'division de colonie', 'división de colonia', 'koloni bölme', 'διαίρεση μελισσιού', { en:['split'], tr:['bölme'] }),
  term('swarm', 'Menaxhimi i kolonisë', 'Grup bletësh që largohet nga kolonia me një mbretëreshë.', 'tufë bletësh', 'swarm', 'sciame', 'Bienenschwarm', 'essaim', 'enjambre', 'oğul', 'σμήνος'),
  term('swarming', 'Menaxhimi i kolonisë', 'Procesi natyror i shumimit me largim të një tufe.', 'tufëzim', 'swarming', 'sciamatura', 'Schwärmen', 'essaimage', 'enjambrazón', 'oğul verme', 'σμηνουργία'),
  term('swarm-control', 'Menaxhimi i kolonisë', 'Praktika për zvogëlimin e prirjes së kolonisë për tufëzim.', 'kontroll i tufëzimit', 'swarm control', 'controllo della sciamatura', 'Schwarmkontrolle', 'contrôle de l’essaimage', 'control de enjambrazón', 'oğul kontrolü', 'έλεγχος σμηνουργίας'),
  term('primary-swarm', 'Menaxhimi i kolonisë', 'Tufa e parë që largohet, zakonisht me mbretëreshën e vjetër.', 'tufë primare', 'primary swarm', 'sciame primario', 'Vorschwarm', 'essaim primaire', 'enjambre primario', 'ilk oğul', 'πρωτοσμήνος'),
  term('afterswarm', 'Menaxhimi i kolonisë', 'Tufë e mëvonshme që largohet pas tufës së parë.', 'tufë dytësore', 'afterswarm', 'sciame secondario', 'Nachschwarm', 'essaim secondaire', 'enjambre secundario', 'artçı oğul', 'δευτεροσμήνος'),
  term('requeening', 'Menaxhimi i kolonisë', 'Zëvendësimi i mbretëreshës me një tjetër.', 'ndërrim mbretëreshe', 'requeening', 'sostituzione della regina', 'Umweiselung', 'remérage', 'reemplazo de reina', 'ana arı yenileme', 'αλλαγή βασίλισσας'),
  term('queen-introduction', 'Mbarështimi i mbretëreshës', 'Futja e një mbretëreshe të re në koloni.', 'futje e mbretëreshës', 'queen introduction', 'introduzione della regina', 'Einweiseln', 'introduction de reine', 'introducción de reina', 'ana arı kabul ettirme', 'εισαγωγή βασίλισσας'),
  term('queen-cage', 'Mbarështimi i mbretëreshës', 'Kafaz i vogël për transport ose futje të mbretëreshës.', 'kafaz mbretëreshe', 'queen cage', 'gabbietta per regina', 'Zusetzkäfig', 'cagette à reine', 'jaula de reina', 'ana arı kafesi', 'κλουβί βασίλισσας'),
  term('queen-marking', 'Mbarështimi i mbretëreshës', 'Shënimi i mbretëreshës me ngjyrë për identifikim.', 'shënim i mbretëreshës', 'queen marking', 'marcatura della regina', 'Königinnenzeichnung', 'marquage de reine', 'marcado de reinas', 'ana arı işaretleme', 'σήμανση βασίλισσας'),
  term('queen-clipping', 'Mbarështimi i mbretëreshës', 'Shkurtim i kontrolluar i krahut të mbretëreshës për menaxhim.', 'prerje krahu e mbretëreshës', 'queen clipping', 'spuntatura dell’ala della regina', 'Flügelschneiden der Königin', 'clippage de reine', 'corte de ala de reina', 'ana arı kanat kesimi', 'κόψιμο φτερού βασίλισσας'),
  term('mating-flight', 'Mbarështimi i mbretëreshës', 'Fluturimi në të cilin mbretëresha virgjër çiftëzohet me meshkujt.', 'fluturim çiftëzimi', 'mating flight', 'volo nuziale', 'Begattungsflug', 'vol nuptial', 'vuelo nupcial', 'çiftleşme uçuşu', 'γαμήλια πτήση'),
  term('orientation-flight', 'Menaxhimi i kolonisë', 'Fluturim i shkurtër për njohjen e mjedisit të kosheres.', 'fluturim orientues', 'orientation flight', 'volo di orientamento', 'Orientierungsflug', 'vol d’orientation', 'vuelo de orientación', 'oryantasyon uçuşu', 'πτήση προσανατολισμού'),
  term('cleansing-flight', 'Menaxhimi i kolonisë', 'Fluturim pas periudhe mbylljeje për zbrazjen e zorrëve.', 'fluturim pastrues', 'cleansing flight', 'volo di purificazione', 'Reinigungsflug', 'vol de propreté', 'vuelo de limpieza', 'temizlik uçuşu', 'πτήση καθαρισμού'),
  term('robbing', 'Menaxhimi i kolonisë', 'Marrja e mjaltit ose nektarit nga një koloni tjetër.', 'plaçkitje', 'robbing', 'saccheggio', 'Räuberei', 'pillage', 'pillaje', 'yağmacılık', 'λεηλασία'),
  term('drift', 'Menaxhimi i kolonisë', 'Hyrja gabimisht e bletëve në koloni fqinje.', 'devijim bletësh', 'drift', 'deriva', 'Verfliegen', 'dérive', 'deriva', 'arı sapması', 'παραπλάνηση μελισσών'),
  term('migratory-beekeeping', 'Menaxhimi i kolonisë', 'Zhvendosja sezonale e koshereve për kullota ose pllenim.', 'bletari shtegtare', 'migratory beekeeping', 'apicoltura nomade', 'Wanderimkerei', 'apiculture transhumante', 'apicultura trashumante', 'gezgin arıcılık', 'νομαδική μελισσοκομία'),
  term('overwintering', 'Menaxhimi i kolonisë', 'Përgatitja dhe mbajtja e kolonisë gjatë dimrit.', 'dimërim', 'overwintering', 'svernamento', 'Einwinterung', 'hivernage', 'invernada', 'kışlatma', 'ξεχειμώνιασμα'),
  term('winter-cluster', 'Menaxhimi i kolonisë', 'Grumbullim i ngushtë i bletëve për ruajtjen e nxehtësisë në dimër.', 'grumbull dimëror', 'winter cluster', 'glomere invernale', 'Wintertraube', 'grappe hivernale', 'racimo invernal', 'kış salkımı', 'χειμερινή μελισσόσφαιρα'),
  term('supplemental-feeding', 'Ushqimi dhe fenologjia', 'Dhënia e ushqimit kur burimet natyrore nuk mjaftojnë.', 'ushqim suplementar', 'supplemental feeding', 'alimentazione supplementare', 'Zusatzfütterung', 'nourrissement complémentaire', 'alimentación suplementaria', 'ek besleme', 'συμπληρωματική τροφοδότηση'),
  term('sugar-syrup', 'Ushqimi dhe fenologjia', 'Tretësirë uji dhe sheqeri për ushqimin e bletëve.', 'shurup sheqeri', 'sugar syrup', 'sciroppo di zucchero', 'Zuckersirup', 'sirop de sucre', 'jarabe de azúcar', 'şeker şurubu', 'σιρόπι ζάχαρης'),
  term('invert-syrup', 'Ushqimi dhe fenologjia', 'Shurup ku saharoza është ndarë në glukozë dhe fruktozë.', 'shurup invert', 'invert syrup', 'sciroppo invertito', 'Invertzuckersirup', 'sirop inverti', 'jarabe invertido', 'invert şurup', 'ιμβερτοποιημένο σιρόπι'),
  term('fondant', 'Ushqimi dhe fenologjia', 'Ushqim i ngurtë me bazë sheqeri për bletët.', 'fondant', 'fondant', 'candito', 'Futterteig', 'candi', 'fondant', 'arı keki', 'ζαχαροζύμαρο'),
  term('pollen-patty', 'Ushqimi dhe fenologjia', 'Masë ushqimore proteinike me polen ose zëvendësues poleni.', 'biskotë poleni', 'pollen patty', 'polpetta proteica', 'Pollenteig', 'galette protéinée', 'torta de polen', 'polen keki', 'γυρεόπιτα'),
  term('nectar-dearth', 'Ushqimi dhe fenologjia', 'Periudhë me mungesë të burimeve të nektarit.', 'mungesë nektari', 'nectar dearth', 'carenza nettarifera', 'Trachtlücke', 'disette nectarifère', 'escasez de néctar', 'nektar kıtlığı', 'έλλειψη νέκταρος'),
  term('honey-flow', 'Ushqimi dhe fenologjia', 'Periudhë me bollëk nektari dhe prodhim rezervash mjalti.', 'kullotë mjalti', 'honey flow', 'flusso nettarifero', 'Tracht', 'miellée', 'flujo de néctar', 'bal akımı', 'ανθοφορία μελιού'),

  // Shëndeti dhe bio-siguria
  term('varroa-destructor', 'Shëndeti dhe bio-siguria', 'Marimangë parazitare e jashtme e bletëve të mjaltit.', 'Varroa destructor', 'Varroa destructor', 'Varroa destructor', 'Varroa destructor', 'Varroa destructor', 'Varroa destructor', 'Varroa destructor', 'Varroa destructor', { en:['varroa mite'], tr:['varroa akarı'], el:['βαρρόα'] }),
  term('varroosis', 'Shëndeti dhe bio-siguria', 'Infestim i kolonisë nga marimanga Varroa.', 'varroatozë', 'varroosis', 'varroatosi', 'Varroose', 'varroose', 'varroosis', 'varroatoz', 'βαρροϊκή ακαρίαση'),
  term('mite-monitoring', 'Shëndeti dhe bio-siguria', 'Vlerësim i ngarkesës së marimangave në koloni.', 'monitorim i marimangave', 'mite monitoring', 'monitoraggio degli acari', 'Milbenmonitoring', 'surveillance des acariens', 'monitoreo de ácaros', 'akar takibi', 'παρακολούθηση ακάρεων'),
  term('sticky-board', 'Shëndeti dhe bio-siguria', 'Fletë ngjitëse për numërimin e rënies së marimangave.', 'tabaka ngjitëse', 'sticky board', 'vassoio appiccicoso', 'Windel', 'lange collante', 'lámina pegajosa', 'yapışkan tabanlık', 'κολλητική επιφάνεια'),
  term('oxalic-acid', 'Shëndeti dhe bio-siguria', 'Acid organik i përdorur në disa protokolle të kontrollit të Varroa-s.', 'acid oksalik', 'oxalic acid', 'acido ossalico', 'Oxalsäure', 'acide oxalique', 'ácido oxálico', 'oksalik asit', 'οξαλικό οξύ'),
  term('formic-acid', 'Shëndeti dhe bio-siguria', 'Acid organik avullues i përdorur në disa protokolle të kontrollit të Varroa-s.', 'acid formik', 'formic acid', 'acido formico', 'Ameisensäure', 'acide formique', 'ácido fórmico', 'formik asit', 'μυρμηκικό οξύ'),
  term('thymol', 'Shëndeti dhe bio-siguria', 'Përbërës aromatik i trumzës, i përdorur në disa produkte bletarie.', 'timol', 'thymol', 'timolo', 'Thymol', 'thymol', 'timol', 'timol', 'θυμόλη'),
  term('ipm', 'Shëndeti dhe bio-siguria', 'Qasje që kombinon monitorimin, praktikat dhe ndërhyrjet e lejuara për dëmtuesit.', 'menaxhim i integruar i dëmtuesve', 'integrated pest management', 'gestione integrata dei parassiti', 'integrierter Pflanzenschutz', 'gestion intégrée des ravageurs', 'manejo integrado de plagas', 'entegre zararlı yönetimi', 'ολοκληρωμένη διαχείριση παρασίτων', { en:['IPM'], tr:['IPM'], el:['IPM'] }),
  term('nosemosis', 'Shëndeti dhe bio-siguria', 'Sëmundje e zorrëve e lidhur me mikrosporidiet Nosema/Vairimorpha.', 'nozemozë', 'nosemosis', 'nosemiasi', 'Nosemose', 'nosémose', 'nosemosis', 'nosemoz', 'νοσεμίαση'),
  term('tracheal-mite', 'Shëndeti dhe bio-siguria', 'Marimangë që prek traketë e bletëve të rritura.', 'marimangë trakeale', 'tracheal mite', 'acaro tracheale', 'Tracheenmilbe', 'acarien trachéal', 'ácaro traqueal', 'trake akarı', 'τραχειακό άκαρι'),
  term('acarine-disease', 'Shëndeti dhe bio-siguria', 'Gjendje e shkaktuar nga Acarapis woodi.', 'akarinozë', 'acarine disease', 'acariosi', 'Acarapiose', 'acariose', 'acariosis', 'akarapis hastalığı', 'ακαρίαση'),
  term('american-foulbrood', 'Shëndeti dhe bio-siguria', 'Sëmundje bakteriale serioze e pjellës e shkaktuar nga Paenibacillus larvae.', 'kalbëzimi amerikan i pjellës', 'American foulbrood', 'peste americana', 'Amerikanische Faulbrut', 'loque américaine', 'loque americana', 'Amerikan yavru çürüklüğü', 'αμερικανική σηψιγονία', { en:['AFB'], tr:['Amerikan yavru çürüklüğü'], el:['Αμερικανική σηψιγονία'] }),
  term('european-foulbrood', 'Shëndeti dhe bio-siguria', 'Sëmundje bakteriale e pjellës e lidhur me Melissococcus plutonius.', 'kalbëzimi evropian i pjellës', 'European foulbrood', 'peste europea', 'Europäische Faulbrut', 'loque européenne', 'loque europea', 'Avrupa yavru çürüklüğü', 'ευρωπαϊκή σηψιγονία', { en:['EFB'] }),
  term('chalkbrood', 'Shëndeti dhe bio-siguria', 'Sëmundje kërpudhore e pjellës që krijon larva të ngurtësuara.', 'pjellë gëlqerore', 'chalkbrood', 'covata calcificata', 'Kalkbrut', 'couvain calcifié', 'cría yesificada', 'kireç hastalığı', 'ασκοσφαίρωση'),
  term('sacbrood', 'Shëndeti dhe bio-siguria', 'Sëmundje virale që prek larvat.', 'pjellë qesore', 'sacbrood', 'covata a sacco', 'Sackbrut', 'couvain sacciforme', 'cría ensacada', 'torba yavru hastalığı', 'σακκόγονος σηψιγονία'),
  term('dwv', 'Shëndeti dhe bio-siguria', 'Virus i lidhur me deformimin e krahëve dhe Varroa-n.', 'virusi i krahëve të deformuar', 'deformed wing virus', 'virus delle ali deformi', 'Flügeldeformationsvirus', 'virus des ailes déformées', 'virus de las alas deformadas', 'deforme kanat virüsü', 'ιός παραμορφωμένων πτερύγων', { en:['DWV'], tr:['DWV'], el:['DWV'] }),
  term('cbpv', 'Shëndeti dhe bio-siguria', 'Virus që lidhet me paralizën kronike të bletëve.', 'virusi i paralizës kronike të bletëve', 'chronic bee paralysis virus', 'virus della paralisi cronica delle api', 'Chronisches-Bienenparalyse-Virus', 'virus de la paralysie chronique des abeilles', 'virus de la parálisis crónica de las abejas', 'kronik arı felci virüsü', 'ιός χρόνιας παράλυσης των μελισσών', { en:['CBPV'] }),
  term('wax-moth', 'Shëndeti dhe bio-siguria', 'Dëmtues, larvat e të cilit dëmtojnë hojet prej dylli.', 'tenja e dyllit', 'wax moth', 'tarma della cera', 'Wachsmotte', 'fausse teigne de la cire', 'polilla de la cera', 'balmumu güvesi', 'κηρόσκωρος'),
  term('small-hive-beetle', 'Shëndeti dhe bio-siguria', 'Dëmtues i kosheres me emrin shkencor Aethina tumida.', 'brumbulli i vogël i kosheres', 'small hive beetle', 'piccolo coleottero dell’alveare', 'Kleiner Beutenkäfer', 'petit coléoptère des ruches', 'pequeño escarabajo de la colmena', 'küçük kovan böceği', 'μικρό σκαθάρι της κυψέλης', { en:['SHB'] }),
  term('bee-louse', 'Shëndeti dhe bio-siguria', 'Mizë pa krahë Braula coeca, e quajtur zakonisht morr blete.', 'morr blete', 'bee louse', 'pidocchio delle api', 'Bienenlaus', 'pou des abeilles', 'piojo de las abejas', 'arı biti', 'ψείρα της μέλισσας'),
  term('tropilaelaps', 'Shëndeti dhe bio-siguria', 'Gjini marimangash parazitare të pjellës së bletëve.', 'Tropilaelaps', 'Tropilaelaps mite', 'acaro Tropilaelaps', 'Tropilaelaps-Milbe', 'acarien Tropilaelaps', 'ácaro Tropilaelaps', 'Tropilaelaps akarı', 'άκαρι Tropilaelaps'),
  term('pesticide-poisoning', 'Shëndeti dhe bio-siguria', 'Dëmtim i bletëve nga ekspozimi ndaj pesticideve.', 'helmim nga pesticidet', 'pesticide poisoning', 'avvelenamento da pesticidi', 'Pestizidvergiftung', 'intoxication aux pesticides', 'intoxicación por pesticidas', 'pestisit zehirlenmesi', 'δηλητηρίαση από φυτοφάρμακα'),
  term('dysentery', 'Shëndeti dhe bio-siguria', 'Gjendje me jashtëqitje në koshere nga faktorë të ndryshëm.', 'dizenteri', 'dysentery', 'dissenteria', 'Ruhr', 'dysenterie', 'disentería', 'dizanteri', 'δυσεντερία'),
  term('hygienic-behavior', 'Shëndeti dhe bio-siguria', 'Aftësi e kolonisë për të zbuluar dhe hequr pjellën e dëmtuar.', 'sjellje higjienike', 'hygienic behavior', 'comportamento igienico', 'Hygieneverhalten', 'comportement hygiénique', 'comportamiento higiénico', 'hijyenik davranış', 'υγιεινή συμπεριφορά'),
  term('vsh', 'Shëndeti dhe bio-siguria', 'Sjellje higjienike specifike ndaj Varroa-s.', 'higjienë e ndjeshme ndaj Varroa-s', 'Varroa sensitive hygiene', 'igiene sensibile alla Varroa', 'Varroa-sensitives Hygieneverhalten', 'hygiène sensible au Varroa', 'higiene sensible a Varroa', 'Varroaya duyarlı hijyen', 'υγιεινή ευαίσθητη στη βαρρόα', { en:['VSH'], tr:['VSH'], el:['VSH'] }),
  term('quarantine', 'Shëndeti dhe bio-siguria', 'Izolim i kontrolluar për kufizimin e përhapjes së sëmundjeve ose dëmtuesve.', 'karantinë', 'quarantine', 'quarantena', 'Quarantäne', 'quarantaine', 'cuarentena', 'karantina', 'καραντίνα'),

  // Produkte dhe përpunim
  term('honey', 'Produkte dhe përpunim', 'Produkt i ëmbël i përpunuar nga nektari ose sekrecione bimore.', 'mjaltë', 'honey', 'miele', 'Honig', 'miel', 'miel', 'bal', 'μέλι'),
  term('raw-honey', 'Produkte dhe përpunim', 'Mjaltë me përpunim minimal pas nxjerrjes.', 'mjaltë i papërpunuar', 'raw honey', 'miele grezzo', 'Rohhonig', 'miel brut', 'miel cruda', 'ham bal', 'ακατέργαστο μέλι'),
  term('comb-honey', 'Produkte dhe përpunim', 'Mjaltë që shitet në hoje.', 'mjaltë në hoje', 'comb honey', 'miele in favo', 'Wabenhonig', 'miel en rayon', 'miel en panal', 'petek balı', 'μέλι κηρήθρας'),
  term('extracted-honey', 'Produkte dhe përpunim', 'Mjaltë i hequr nga hoje me ekstraktor.', 'mjaltë i nxjerrë', 'extracted honey', 'miele estratto', 'Schleuderhonig', 'miel extrait', 'miel extraída', 'süzme bal', 'εξαγόμενο μέλι'),
  term('creamed-honey', 'Produkte dhe përpunim', 'Mjaltë i kristalizuar në mënyrë të kontrolluar për teksturë të butë.', 'mjaltë kremoz', 'creamed honey', 'miele cremoso', 'Cremehonig', 'miel crémeux', 'miel cremosa', 'krem bal', 'κρεμώδες μέλι'),
  term('chunk-honey', 'Produkte dhe përpunim', 'Mjaltë i lëngshëm me një copë hoje brenda enës.', 'mjaltë me hoje', 'chunk honey', 'miele con favo', 'Honig mit Wabenstück', 'miel en morceaux de rayon', 'miel con trozo de panal', 'petekli bal', 'μέλι με κομμάτι κηρήθρας'),
  term('honeydew-honey', 'Produkte dhe përpunim', 'Mjaltë nga sekrecionet e ëmbla të insekteve mbi bimë.', 'mjaltë mjaltiçare', 'honeydew honey', 'miele di melata', 'Honigtauhonig', 'miel de miellat', 'miel de mielada', 'çam balı', 'μέλι μελιτώματος'),
  term('cappings', 'Produkte dhe përpunim', 'Kapakë dylli që mbyllin qelizat e plota me mjaltë.', 'kapakë dylli', 'cappings', 'opercoli', 'Wachsdeckel', 'opercules', 'opérculos', 'bal sırları', 'λεπιδάκια κηρήθρας'),
  term('beeswax', 'Produkte dhe përpunim', 'Dyll natyror i prodhuar nga gjendrat e punëtoreve.', 'dyll blete', 'beeswax', 'cera d’api', 'Bienenwachs', 'cire d’abeille', 'cera de abeja', 'balmumu', 'κερί μέλισσας'),
  term('propolis', 'Produkte dhe përpunim', 'Substancë rrëshinore që bletët e përdorin për mbyllje dhe mbrojtje.', 'propolis', 'propolis', 'propoli', 'Propolis', 'propolis', 'propóleo', 'propolis', 'πρόπολη'),
  term('royal-jelly', 'Produkte dhe përpunim', 'Sekrecion ushqyes për larvat e reja dhe mbretëreshën.', 'pelte mbretërore', 'royal jelly', 'pappa reale', 'Gelée Royale', 'gelée royale', 'jalea real', 'arı sütü', 'βασιλικός πολτός'),
  term('pollen', 'Produkte dhe përpunim', 'Burim kryesor proteinash për koloninë.', 'polen', 'pollen', 'polline', 'Pollen', 'pollen', 'polen', 'polen', 'γύρη'),
  term('bee-bread', 'Produkte dhe përpunim', 'Polen i ruajtur dhe i fermentuar në hoje.', 'bukë blete', 'bee bread', 'pane d’api', 'Bienenbrot', 'pain d’abeille', 'pan de abeja', 'arı ekmeği', 'μελισσόψωμο'),
  term('bee-venom', 'Produkte dhe përpunim', 'Sekrecion i aparatit helmues të bletës.', 'helm blete', 'bee venom', 'veleno d’api', 'Bienengift', 'venin d’abeille', 'veneno de abeja', 'arı zehiri', 'δηλητήριο μέλισσας'),
  term('mead', 'Produkte dhe përpunim', 'Pije e fermentuar me bazë mjalti.', 'verë mjalti', 'mead', 'idromele', 'Met', 'hydromel', 'hidromiel', 'bal şarabı', 'υδρόμελι'),
  term('extraction', 'Produkte dhe përpunim', 'Procesi i nxjerrjes së mjaltit nga hoje.', 'nxjerrje mjalti', 'honey extraction', 'smielatura', 'Honigernte', 'extraction du miel', 'extracción de miel', 'bal sağımı', 'εξαγωγή μελιού'),
  term('clarifier', 'Produkte dhe përpunim', 'Enë ku mjalti qetësohet për ndarjen e dyllit dhe papastërtive.', 'depozitë qartësimi', 'clarifying tank', 'maturatore', 'Klärbehälter', 'bac de décantation', 'tanque decantador', 'dinlendirme tankı', 'δεξαμενή καθίζησης'),
  term('bottling', 'Produkte dhe përpunim', 'Mbushja e mjaltit në kavanoza ose enë shitjeje.', 'mbushje në kavanoza', 'bottling', 'invasettamento', 'Abfüllen', 'mise en pot', 'envasado', 'kavanozlama', 'εμφιάλωση'),
  term('crystallization', 'Produkte dhe përpunim', 'Formimi i kristaleve të sheqerit në mjaltë.', 'kristalizim', 'crystallization', 'cristallizzazione', 'Kristallisation', 'cristallisation', 'cristalización', 'kristalleşme', 'κρυστάλλωση'),
  term('fermentation', 'Produkte dhe përpunim', 'Proces mikrobiologjik që mund të ndryshojë mjaltin me lagështi të lartë.', 'fermentim', 'fermentation', 'fermentazione', 'Gärung', 'fermentation', 'fermentación', 'fermantasyon', 'ζύμωση'),
  term('moisture-content', 'Produkte dhe përpunim', 'Përqindja e ujit në mjaltë.', 'përmbajtje lagështie', 'moisture content', 'contenuto di umidità', 'Wassergehalt', 'taux d’humidité', 'contenido de humedad', 'nem oranı', 'περιεκτικότητα υγρασίας'),
  term('hmf', 'Produkte dhe përpunim', 'Hidroksimetilfurfural, tregues analitik i cilësisë së mjaltit.', 'hidroksimetilfurfural', 'hydroxymethylfurfural', 'idrossimetilfurfurale', 'Hydroxymethylfurfural', 'hydroxyméthylfurfural', 'hidroximetilfurfural', 'hidroksimetilfurfural', 'υδροξυμεθυλοφουρφουράλη', { en:['HMF'], tr:['HMF'], el:['HMF'] }),
  term('diastase', 'Produkte dhe përpunim', 'Enzimë e matur në disa analiza të cilësisë së mjaltit.', 'diastazë', 'diastase', 'diastasi', 'Diastase', 'diastase', 'diastasa', 'diastaz', 'διαστάση'),
  term('ripening', 'Produkte dhe përpunim', 'Pjekja e nektarit në mjaltë përmes uljes së lagështisë dhe ndryshimeve enzimatike.', 'pjekje e mjaltit', 'honey ripening', 'maturazione del miele', 'Honigreifung', 'maturation du miel', 'maduración de la miel', 'bal olgunlaşması', 'ωρίμανση μελιού'),
  term('honey-stomach', 'Biologjia dhe sjellja e bletës', 'Organ i zgjerueshëm ku bleta bart nektar ose ujë.', 'stomak mjalti', 'honey stomach', 'borsa melaria', 'Honigmagen', 'jabot', 'buche melífero', 'bal midesi', 'μελιτοστομάχι'),

  // Bimët, pllenimi dhe mjedisi
  term('nectar', 'Bimët, pllenimi dhe mjedisi', 'Lëng i ëmbël i luleve, lëndë e parë për mjaltin.', 'nektar', 'nectar', 'nettare', 'Nektar', 'nectar', 'néctar', 'nektar', 'νέκταρ'),
  term('forage', 'Bimët, pllenimi dhe mjedisi', 'Burime bimore të nektarit dhe polenit për bletët.', 'kullotë bletësh', 'bee forage', 'risorse nettarifere', 'Bienenweide', 'ressources mellifères', 'flora apícola', 'arı merası', 'μελισσοβοσκή'),
  term('nectary', 'Bimët, pllenimi dhe mjedisi', 'Pjesa e lules ose bimës që prodhon nektar.', 'nektari', 'nectary', 'nettario', 'Nektarium', 'nectaire', 'nectario', 'nektar bezi', 'νεκτάριο'),
  term('pollination', 'Bimët, pllenimi dhe mjedisi', 'Transferimi i polenit për riprodhimin e bimëve.', 'pllenim', 'pollination', 'impollinazione', 'Bestäubung', 'pollinisation', 'polinización', 'tozlaşma', 'επικονίαση'),
  term('pollinator', 'Bimët, pllenimi dhe mjedisi', 'Organizëm që bart polenin ndërmjet luleve.', 'pjalmues', 'pollinator', 'impollinatore', 'Bestäuber', 'pollinisateur', 'polinizador', 'tozlayıcı', 'επικονιαστής'),
  term('pollenizer', 'Bimët, pllenimi dhe mjedisi', 'Bimë që furnizon polen për pllenim të kryqëzuar.', 'bimë polenizuese', 'pollenizer', 'pianta impollinatrice', 'Pollenspenderpflanze', 'plante pollinisatrice', 'planta polinizadora', 'tozlayıcı bitki', 'γυρεοδότρια ποικιλία'),
  term('cross-pollination', 'Bimët, pllenimi dhe mjedisi', 'Kalimi i polenit midis bimëve të ndryshme të së njëjtës specie.', 'pllenim i kryqëzuar', 'cross-pollination', 'impollinazione incrociata', 'Fremdbestäubung', 'pollinisation croisée', 'polinización cruzada', 'çapraz tozlaşma', 'σταυρεπικονίαση'),
  term('apiary-site', 'Bimët, pllenimi dhe mjedisi', 'Vendndodhja e zgjedhur për bletore.', 'vendndodhje bletoreje', 'apiary site', 'sito dell’apiario', 'Bienenstandort', 'emplacement du rucher', 'ubicación del apiario', 'arı kovanlığı yeri', 'τοποθεσία μελισσοκομείου'),
  term('black-locust', 'Bimët, pllenimi dhe mjedisi', 'Pemë mellifere Robinia pseudoacacia, e njohur si akacie e zezë.', 'akacie e zezë', 'black locust', 'robinia', 'Robinie', 'robinier faux-acacia', 'falsa acacia', 'yalancı akasya', 'ψευδοακακία'),
  term('linden', 'Bimët, pllenimi dhe mjedisi', 'Pemë mellifere e gjinisë Tilia.', 'bli', 'linden', 'tiglio', 'Linde', 'tilleul', 'tilo', 'ıhlamur', 'φλαμουριά'),
  term('chestnut', 'Bimët, pllenimi dhe mjedisi', 'Pemë mellifere e gjinisë Castanea.', 'gështenjë', 'chestnut', 'castagno', 'Kastanie', 'châtaignier', 'castaño', 'kestane', 'καστανιά'),
  term('sunflower', 'Bimët, pllenimi dhe mjedisi', 'Bimë kultivuese mellifere Helianthus annuus.', 'luledielli', 'sunflower', 'girasole', 'Sonnenblume', 'tournesol', 'girasol', 'ayçiçeği', 'ηλίανθος'),
  term('lavender', 'Bimët, pllenimi dhe mjedisi', 'Bimë aromatike e gjinisë Lavandula, burim nektari.', 'livando', 'lavender', 'lavanda', 'Lavendel', 'lavande', 'lavanda', 'lavanta', 'λεβάντα'),
  term('thyme', 'Bimët, pllenimi dhe mjedisi', 'Bimë aromatike e gjinisë Thymus, burim nektari.', 'trumzë', 'thyme', 'timo', 'Thymian', 'thym', 'tomillo', 'kekik', 'θυμάρι'),
  term('rosemary', 'Bimët, pllenimi dhe mjedisi', 'Bimë aromatike Rosmarinus/Salvia rosmarinus, burim nektari.', 'rozmarinë', 'rosemary', 'rosmarino', 'Rosmarin', 'romarin', 'romero', 'biberiye', 'δενδρολίβανο')
];

const QUICK_TERM_IDS = [
  'queen-bee', 'varroa-destructor', 'hive', 'frame', 'honey', 'propolis',
  'extractor', 'requeening', 'pollen-trap', 'brood', 'sugar-syrup', 'nectar'
];

const GLOSSARY_META = {
  version: '2.0.0',
  description: 'Fjalor teknik shumëgjuhësh i bletarisë, i ndërtuar për përdorim lokal.',
  languageCount: LANGUAGES.length,
  termCount: GLOSSARY.length
};
